# Numpy Array 
Tek veri tipine sahiptir.

Bilimsel işlemler için kullanılan çok gelişmiş bir kütüphanedir.

## Numpy Array Oluşturma

In [139]:
import numpy as np
array = np.array([1,2,3,4,5,6])
print(array)

[1 2 3 4 5 6]


In [140]:
a = np.zeros((2,2))   # Create an array of all zeros
print(a)             
                     
b = np.ones((1,2))    # Create an array of all ones
print(b)              

c = np.full((2,2), 7)  # Create a constant array
print(c)               

d = np.eye(2)         # Create a 2x2 identity matrix
print(d)              

e = np.random.random((2,2))  # Create an array random values
print(e)       

f = np.arange(1,30,3) # Create an lineer array
print(f)

g = np.random.randint(20, size = 10) # Create random intetgers
print(g)

l = np.random.normal(20,5, (3,3)) # mean 20, std 5, shape (3,3)

[[0. 0.]
 [0. 0.]]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[0.3879807  0.47180724]
 [0.41468476 0.01013212]]
[ 1  4  7 10 13 16 19 22 25 28]
[ 9  3 11  8 12 11 19 11  7  5]


## Array Methods

### Array Info

In [141]:
import numpy as np

In [142]:
matrixNp = np.random.randint(10, size = (3,3))
print(matrixNp)

[[3 9 8]
 [3 6 7]
 [9 4 0]]


In [143]:
print(matrixNp.ndim) # dimention
print(matrixNp.shape)
print(matrixNp.size)
print(matrixNp.dtype)

2
(3, 3)
9
int32


### Reshaping

In [144]:
import numpy as np

In [145]:
print(np.arange(3,28,3).reshape(3,3))

[[ 3  6  9]
 [12 15 18]
 [21 24 27]]


### Concat

In [146]:
import numpy as np

#### 1D

In [147]:
x = np.arange(1,24)
y = np.arange(40,20,-1)
z = np.arange(40,61)
xyz = np.concatenate([x,y,z]).reshape(8,8)
print(xyz)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]
 [17 18 19 20 21 22 23 40]
 [39 38 37 36 35 34 33 32]
 [31 30 29 28 27 26 25 24]
 [23 22 21 40 41 42 43 44]
 [45 46 47 48 49 50 51 52]
 [53 54 55 56 57 58 59 60]]


#### 2D

In [148]:
x2d = np.arange(1,7).reshape(2,3)
y2d = np.arange(8,14).reshape(2,3)
z2d = np.arange(15,21).reshape(2,3)

In [149]:
xyz2d = np.concatenate([x2d,y2d,z2d])
print(xyz2d)

[[ 1  2  3]
 [ 4  5  6]
 [ 8  9 10]
 [11 12 13]
 [15 16 17]
 [18 19 20]]


In [150]:
xyz2d = np.concatenate([x2d,y2d,z2d], axis = 1)
print(xyz2d)

[[ 1  2  3  8  9 10 15 16 17]
 [ 4  5  6 11 12 13 18 19 20]]


### Splitting

In [151]:
import numpy as np

#### 1D

In [152]:
splitArr = np.arange(2,30)
a,b,c,d,e,f,g,l = np.split(splitArr, np.arange(5,30,4))
for letter in "abcdefg":
    print(locals()[letter])


[2 3 4 5 6]
[ 7  8  9 10]
[11 12 13 14]
[15 16 17 18]
[19 20 21 22]
[23 24 25 26]
[27 28 29]


#### 2D

In [153]:
splitArr2d = np.arange(16).reshape(4,4)
verticalTop, verticalBot = np.vsplit(splitArr2d, [2])
horizonalLeft, horizonalRigth = np.hsplit(splitArr2d, [2])

In [154]:
print(verticalTop)
print(verticalBot)
print(horizonalRigth)
print(horizonalLeft)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


### Sorting

In [155]:
import numpy as np

#### 1D

In [156]:
randomArr = np.random.randint(10,100, size = 20)
sortedArr = np.sort(randomArr)
print(randomArr, "\n", sortedArr)

[63 13 85 46 74 66 88 75 84 34 19 21 68 81 26 33 87 94 23 55] 
 [13 19 21 23 26 33 34 46 55 63 66 68 74 75 81 84 85 87 88 94]


#### 2D

In [157]:
randomArr2d = np.random.normal(20,5, (3,3))

In [158]:
print(np.sort(randomArr2d, axis = 1))
print(np.sort(randomArr2d, axis = 0))

[[16.10425892 20.21417328 26.13504076]
 [ 9.29776489 20.84521013 21.49351778]
 [13.88832037 16.24977777 24.26125737]]
[[16.24977777 13.88832037  9.29776489]
 [20.21417328 21.49351778 16.10425892]
 [20.84521013 26.13504076 24.26125737]]


##### 2D sort by lineer

In [159]:
print(np.sort(randomArr2d.reshape(1,randomArr2d.size)).reshape(3,3))

[[ 9.29776489 13.88832037 16.10425892]
 [16.24977777 20.21417328 20.84521013]
 [21.49351778 24.26125737 26.13504076]]


### Slicing Operations

In [160]:
import numpy as np

#### 1D

In [161]:
indexArr = np.random.randint(0, 10, size = 20)
print(indexArr)
print(indexArr[0],indexArr[-1])

[9 4 3 2 1 0 9 1 6 7 3 0 2 0 9 3 1 6 5 2]
9 2


In [162]:
print(indexArr[0:4])
print(indexArr[:4])
print(indexArr[4:])
print(indexArr[1::4])
print(indexArr[::-2])

[9 4 3 2]
[9 4 3 2]
[1 0 9 1 6 7 3 0 2 0 9 3 1 6 5 2]
[4 0 7 0 6]
[2 6 3 0 0 7 1 0 2 4]


#### 2D

In [163]:
indexArr2d = np.random.randint(10, size = (5,5))
print(indexArr2d)

[[5 1 6 7 1]
 [7 1 7 3 1]
 [2 1 1 1 8]
 [5 5 6 6 0]
 [3 9 1 7 5]]


In [164]:
print("1", indexArr2d[:,0])
print("2",indexArr2d[:,1])
print("3",indexArr2d[:,4])
print("4",indexArr2d[0,:])
print("5",indexArr2d[0])
print("6",indexArr2d[2:3,0:3])
print("7",indexArr2d[:,0:2])
print("8",indexArr2d[1:3,0:2])

1 [5 7 2 5 3]
2 [1 1 1 5 9]
3 [1 1 8 0 5]
4 [5 1 6 7 1]
5 [5 1 6 7 1]
6 [[2 1 1]]
7 [[5 1]
 [7 1]
 [2 1]
 [5 5]
 [3 9]]
8 [[7 1]
 [2 1]]


### Fancy Index ile Elemanlara Erişmek

In [165]:
import numpy as np

#### 1D

In [166]:
v = np.arange(0, 30, 3)
print(v[1],v[3],v[5])
[v[1], v[3], v[5]]

fancy = [1,3,5]
v[fancy]

3 9 15


array([ 3,  9, 15])

#### 2D

In [167]:
m = np.arange(9).reshape((3,3))
print(m)
row = np.array([0,1])
colunm = np.array([1,2])
print(m[row, colunm])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[1 5]


Basit index ile fancy index

In [168]:
print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [169]:
m[0, [1,2]]

array([1, 2])

Fancy ile Slice index

In [170]:
m[0:, [1,2]]

array([[1, 2],
       [4, 5],
       [7, 8]])